config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  root 'static_pages#top'
  
  # トップページ
  get '/signup', to: 'users#new'
  
  # SAについて
  get '/about', to: 'users#about'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  # イベントページ
  get 'event_signup', to: 'events#event_signup'
  post 'event_new', to: 'events#create'
  delete '/destroy', to: 'events#destroy'
  get 'event_edit', to: 'events#event_edit'
  patch 'event_update', to: 'events#event_update'
  
  # プライベートボックスページ
  
  resources :users do
    member do 
    end
    resources :pboxes do
      member do
      end
    end
    resources :refrigerators do
      member do
      end
    end
  end
end

app/models/pbox.rb
class Pbox < ApplicationRecord
  belongs_to :user
  validates :pbox_name,  presence: true, length: { maximum: 50 }
end

app/controllers/pboxes_controller.rb
class PboxesController < ApplicationController
  
  def index
    @user = User.find(params[:user_id])
    @pboxes = current_user.pboxes.where(id: 1..999)
  end
  
  def new
    @user = User.find(params[:user_id])
    @pbox = Pbox.new
  end
  
  def create
    @user = User.find(params[:user_id])
    @pbox = @user.pboxes.new(pbox_params)
    if @pbox.save
      flash[:success] = 'ボックスにアイテムを追加しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = '名前が入力されていません'
      redirect_back(fallback_location: root_path)
    end
  end
  
  def edit
    @pbox = Pbox.find(params[:id])
  end
  
  def update
    @pbox = Pbox.find(params[:id])
    if @pbox.update_attributes(pbox_params)
      flash[:success] = 'データを更新しました'
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
    @pbox = Pbox.find(params[:id])
    @pbox.destroy
    flash[:success] = "データを削除しました"
    redirect_back(fallback_location: root_path)
  end
  
  private # strongparameterの設定

    def pbox_params
      params.require(:pbox).permit(:pbox_name)
    end
end

app/helpers/pboxes_helper.rb
module PboxesHelper
end

app/views/pboxes/_edit.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h2 class="modal-title">プライベートボックス編集</h2>
    </div>
    
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          
          <%= form_with(model: @pbox, url: user_pbox_path, local: true, method: :patch) do |f| %>

          <%= f.label :"名前", class: "eventname" %>
          <%= f.text_field :pbox_name, class: "form-control" %>

          <%= f.submit "更新", class: "btn btn-primary btn-block signup" %>
          
          <% end %>
        </div>
      </div>
    </div>
    
    </div>
  </div>

app/views/pboxes/_new.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h2 class="modal-title">新規登録</h2>
    </div>
    
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          
          <%= form_with(model: @pbox, url: user_pboxes_path(@user), local: true, method: :post) do |f| %>

            <%= f.label :"名前", class: "eventname" %>
            <%= f.text_field :pbox_name, class: "form-control" %>

          <%= f.submit "新規登録", class: "btn btn-primary btn-block signup" %>
          
          <% end %>
         
        </div>
      </div>
    </div>
    
    </div>
  </div>

app/views/pboxes/_show.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h2 class="modal-title">新規登録</h2>
    </div>
    
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
         てすと 
         
        </div>
      </div>
    </div>
    
    </div>
  </div>

app/views/pboxes/index.html.erb
<% provide(:title) %>

  <table class="col-md-6 col-md-offset-3 information">
    <tr>
      <th>名前</th>
      <th>入居中のSA</th>
      <th>部屋番号</th>
    </tr>
    <tr>
      <td><span><%= @user.name %></span></td>
      <td><span><%= @user.department %></span></td>
      <td><span><%= @user.room %></span></td>
    </tr>
  </table>

<table class="col-md-12 menu_header center">
  <tr>
    <td class="col-md-4">
      <%= link_to "イベントスケジュール", {controller: "users", action: "show", id: current_user.id}, local: true, class: "event_link" %>
    </td>
    <td class="col-md-4" style="background-color:#434343;">プライベートボックス</td>
    <td class="col-md-4"><%= link_to "冷蔵・冷凍庫内保管物", {controller: "refrigerators", action: "index", id: current_user.id}, local: true, class: "pbox_link" %></td>
  </tr>
</table>

<div class="col-md-12 event_menu center">
  <table class="col-md-12 event_menu_header">
    <tr>
      <td>名前</td>
      <td class="col-md-1">編集</td>
      <td class="col-md-1">削除</td>
    </tr>
    
    <% @pboxes.each do |pbox| %>
    <tr>
      <td><%= pbox.pbox_name %></td>
      <td><%= link_to "編集", edit_user_pbox_path(id: pbox.id), remote: true, class: "btn btn-success" %></td>
      <td><%= link_to "削除", user_pbox_path(id: pbox.id), method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </table>
</div>

<%= link_to "新規登録", new_user_pbox_path(@user), remote: true, class: "col-md-4 col-md-offset-4 center new_event" %>

<!--モーダルウインドウ表示-->
<div id="new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>