config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  root 'static_pages#top'
  
  # トップページ
  get '/signup', to: 'users#new'
  
  # SAについて
  get '/about', to: 'users#about'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  # イベントページ
  get 'event_signup', to: 'events#event_signup'
  post 'event_new', to: 'events#create'
  delete '/destroy', to: 'events#destroy'
  get 'event_edit', to: 'events#event_edit'
  patch 'event_update', to: 'events#event_update'
  
  # プライベートボックスページ
  
  resources :users do
    member do 
    end
    resources :pboxes do
      member do
      end
    end
    resources :refrigerators do
      member do
      end
    end
  end
end

app/models/refrigerator.rb
class Refrigerator < ApplicationRecord
  belongs_to :user
  validates :name,  presence: true, length: { maximum: 50 }
  validates :expiration_date,  presence: true
end

app/controllers/refrigerators_controller.rb
class RefrigeratorsController < ApplicationController
  
  def index
    @user = User.find(params[:user_id])
    @refrigerators = current_user.refrigerators.where(id: 1..999)
    @refrigerator = @refrigerators.first
  end
  
  def new
    @user = User.find(params[:user_id])
    @refrigerator = Refrigerator.new
  end
  
  def create
    @user = User.find(params[:user_id])
    @refrigerator = @user.refrigerators.new(refrigerator_params)
    if @refrigerator.save
      flash[:success] = '冷蔵・冷凍庫に食品を追加しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = '名前、賞味期限が入力されていません'
      redirect_back(fallback_location: root_path)
    end
  end
  
  def edit
    @refrigerator = Refrigerator.find(params[:id])
  end
  
  def update
    @refrigerator = Refrigerator.find(params[:id])
    if @refrigerator.update_attributes(refrigerator_params)
      flash[:success] = 'データを更新しました'
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
    @refrigerator = Refrigerator.find(params[:id])
    @refrigerator.destroy
    flash[:success] = "データを削除しました"
    redirect_back(fallback_location: root_path)
  end
  
  private # strongparameterの設定

    def refrigerator_params
      params.require(:refrigerator).permit(:name, :expiration_date)
    end
  
end

app/helpers/refrigerators_helper.rb
module RefrigeratorsHelper
end

app/views/refrigerators/_edit.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h2 class="modal-title">冷蔵・冷凍庫保管物編集</h2>
    </div>
    
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          
          <%= form_with(model: @refrigerator, url: user_refrigerator_path, local: true, method: :patch) do |f| %>

          <%= f.label :"名前", class: "eventname" %>
          <%= f.text_field :name, class: "form-control" %>
          
          <%= f.label :"賞味期限", class: "expiration_date" %>
          <%= f.date_field :expiration_date, class: "form-control" %>

          <%= f.submit "更新", class: "btn btn-primary btn-block signup" %>
          
          <% end %>
        </div>
      </div>
    </div>
    
    </div>
  </div>

app/views/refrigerators/_new.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h2 class="modal-title">新規登録</h2>
    </div>
    
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          
          <%= form_with(model: @refrigerator, url: user_refrigerators_path(@user), local: true, method: :post) do |f| %>

            <%= f.label :"名前", class: "eventname" %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :"賞味期限", class: "expiration_date" %>
            <%= f.date_field :expiration_date, class: "form-control" %>

          <%= f.submit "新規登録", class: "btn btn-primary btn-block signup" %>
          
          <% end %>
         
        </div>
      </div>
    </div>
    
    </div>
  </div>

app/views/refrigerators/edit.js.erb
$("#edit").html("<%= escape_javascript(render 'edit') %>");
$("#edit").modal("show");

app/views/refrigerators/index.html.erb
<% provide(:title) %>

  <table class="col-md-6 col-md-offset-3 information">
    <tr>
      <th>名前</th>
      <th>入居中のSA</th>
      <th>部屋番号</th>
    </tr>
    <tr>
      <td><span><%= @user.name %></span></td>
      <td><span><%= @user.department %></span></td>
      <td><span><%= @user.room %></span></td>
    </tr>
  </table>

<table class="col-md-12 menu_header center">
  <tr>
    <td class="col-md-4">
      <%= link_to "イベントスケジュール", {controller: "users", action: "show", id: current_user.id}, local: true, class: "event_link" %>
    </td>
    <td class="col-md-4">
      <%= link_to "プライベートボックス", {controller: "pboxes", action: "index", id: current_user.id}, local: true, class: "event_link" %>
    </td>
    <td class="col-md-4" style="background-color:#434343;">共用冷蔵庫</td>
    
  </tr>
</table>

<div class="col-md-12 event_menu center">
  
  <div class="removal_day">次回冷蔵庫整理日：<%= l(@user.removal_day, format: :long) %></div>

  <table class="col-md-12 event_menu_header">
    <tr>
      <td>名前</td>
      <td class="col-md-2">賞味期限</td>
      <td class="col-md-1">編集</td>
      <td class="col-md-1">削除</td>
    </tr>
    
    <% @refrigerators.each do |refrigerator| %>
    <tr>
      <td><%= refrigerator.name %></td>
      <td><%= l(refrigerator.expiration_date, format: :long) %></td>
      <td><%= link_to "編集", edit_user_refrigerator_path(id: refrigerator.id), remote: true, class: "btn btn-success" %></td>
      <td><%= link_to "削除", user_refrigerator_path(id: refrigerator.id), method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </table>
</div>

<%= link_to "新規登録", new_user_refrigerator_path(@user), remote: true, class: "col-md-4 col-md-offset-4 center new_event" %>

<!--モーダルウインドウ表示-->
<div id="new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/refrigerators/new.js.erb
$("#new").html("<%= escape_javascript(render 'new') %>");
$("#new").modal("show");