config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  root 'static_pages#top'
  
  # トップページ
  get '/signup', to: 'users#new'
  
  # SAについて
  get '/about', to: 'users#about'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  # イベントページ
  get 'event_signup', to: 'events#event_signup'
  post 'event_new', to: 'events#create'
  delete '/destroy', to: 'events#destroy'
  get 'event_edit', to: 'events#event_edit'
  patch 'event_update', to: 'events#event_update'
  
  # プライベートボックスページ
  
  resources :users do
    member do 
    end
    resources :pboxes do
      member do
      end
    end
    resources :refrigerators do
      member do
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pboxes, dependent: :destroy
  has_many :refrigerators, dependent: :destroy
  
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..20 }, allow_blank: true
  validates :room, length: { in: 2..3 }, allow_blank: true
  has_secure_password
  
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @events = Event.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規ユーザーを登録しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :department ,:room, :removal_day)
    end

    # beforeフィルター

    # paramsハッシュからユーザーを取得します。
    def set_user
      @user = User.find(params[:id])
    end

    # ログイン済みのユーザーか確認します。
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    # アクセスしたユーザーが現在ログインしているユーザーか確認します。
    def correct_user
      redirect_to(root_url) unless current_user?(@user)
    end

    # システム管理権限所有かどうか判定します。
    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

<div class="name">
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
</div>

<div class="mail-address2">
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
</div>

<div class="department">
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>
</div>

<div class="room">
  <%= f.label :room, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :room, class: "form-control" %>
</div>

<div class="room">
  <%= f.label :removal_day, class: "label-#{yield(:class_text)}" %>
  <%= f.date_field :removal_day, class: "form-control" %>
</div>

<div class="password">
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
</div>

<div class="password2">
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
</div>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/about.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1 class="h1_text">ソーシャルアパートメントについて</h1>

<div id="youtube-movie">
  <div id="youtube-movie-content">
    <div id="player" style="text-align: center;"></div>  
  </div>
</div>


<script src="//www.youtube.com/iframe_api"></script>

<script type="text/javascript">  
var onYouTubeIframeAPIReady = function(){  
    var player = new YT.Player("player", {  
        videoId: "5n-j7gAKqP0", // 再生する動画のYouTube ID  
        width : 800,　// プレイヤーの幅  
        height: 600,　// プレイヤーの高さ
        playerVars: {
        autoplay: 1, // 自動再生の設定
        loop: 99 // ループの設定
      },
        // ↓イベント設定↓  
        events: {  
            'onStateChange': onPlayerStateChange // 状態が変更された時  
        } 
        
　　　　// ↑イベント設定↑  
    });  
};  
// 状態が変更された時  
function onPlayerStateChange(event) {  
    // 現在のプレーヤーの状態を取得  
    var status = event.data;  
    // 再生終了時  
    if (status == YT.PlayerState.ENDED) {  
        // ↓任意の処理を記述↓  
　　　　console.log("--再生終了しました。--");  
　　　　// ↑任意の処理を記述↑  
    }  
}  
</script>  

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1 class="h1_text">ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1 class="h1_text">ユーザー一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td>
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1 class="h1_text">新規ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title) %>
  <table class="col-md-6 col-md-offset-3 information">
    <tr>
      <th>名前</th>
      <th>入居中のSA</th>
      <th>部屋番号</th>
    </tr>
    <tr>
      <td><span><%= @user.name %></span></td>
      <td><span><%= @user.department %></span></td>
      <td><span><%= @user.room %></span></td>
    </tr>
  </table>


<table class="col-md-12 menu_header center">
  <tr>
    <td class="col-md-4" style="background-color:#434343;">イベントスケジュール</td>
    <td class="col-md-4"><%= link_to "プライベートボックス", user_pboxes_path(@user.id), local: true, class: "pbox_link" %></td>
    <td class="col-md-4"><%= link_to "冷蔵・冷凍庫内保管物", user_refrigerators_path(@user.id), local: true, class: "pbox_link" %></td>
  </tr>
</table>

<div class="col-md-12 event_menu center">
  <table class="col-md-12 event_menu_header">
    <tr>
      
      <td>イベント名</td>
      <td>イベント詳細</td>
      <td>開催場所</td>
      <td>開催日程</td>
      <% if current_user.admin? %>
        <td>編集</td>
        <td>削除</td>
      <% end %>
      
    </tr>
    
    <% @events.each do |event| %>
    <tr>
      
      <td class="col-md-2"><%= event.eventname %></td>
      <td style="text-align:left; padding:5px 5px 5px 6px;"><%= event.eventdetail %></td>
      <td class="col-md-2"><%= event.place %></td>
      <td class="col-md-2"><%= l(event.eventday, format: :long) %></td>
      <% if current_user.admin? %>
        <td class="col-md-1">
          <%= link_to "編集", {controller: "events", action: "event_edit", id: event.id}, remote: true, class: "btn btn-success" %>
        </td>
      <td class="col-md-1">
          <%= link_to "削除", {controller: "events", action: "destroy", id: event.id}, method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
        <% else %>
        <% end %>
      </td>
     
    </tr>
    <% end %>
  </table>
</div>
<% if current_user.admin? %>
  <%= link_to "新規イベント登録", event_signup_path, remote: true, class: "col-md-4 col-md-offset-4 center new_event" %>
<% end %>
<!--モーダルウインドウ表示-->
<div id="event_signup" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="event_edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
 